name: Weekly PR + Slack Notification

on:
  schedule:
    - cron: "45 14 * * 1"  # 8:45am CST every Monday
  workflow_dispatch:

jobs:
  weekly-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run PR and Slack notifier
        env:
          GH_ENTERPRISE_TOKEN: ${{ secrets.GH_ENTERPRISE_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: python create_pr_and_notify.py
